database:
  dbname: "test"
  username: "postgres"
  password: "Fhukh9m1lBlwA41UACEGvg=="
  host: "localhost"
  port: 5432

security:
#when enabled: password has to be encrypted with compiled key in util/encryption/encryption.go
  enabled: true